server:
  port: 18080
spring:
  application:
    name: userservice
  # Database 
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Taipei
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      break-after-acquire-failure: true
      connection-error-retry-attempts: 10
      time-between-connect-error-millis: 1000
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

  # JPA
  jpa:
    show-sql: true

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    host: 127.0.0.1:2181
    address: zookeeper://${dubbo.registry.host}

#====================================Seata Config===============================================
# Ref : https://github.com/seata/seata/blob/master/script/client/spring/application.yml
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
    enable-degrade: false
    disable-global-transaction: false